/*
 * createUserStuffInterFacen.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.Date;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import daos.AccessDAOImpl;
import daos.AccessDAOinf;
import daos.ExcelDAOimpl;
import daos.ExcelDAOinf;
import daos.InventoryBeanDAOimpl;
import daos.InventoryBeanDAOinf;
import daos.SetDAOimpl;
import daos.SetDAOinf;

import beans.AccessBean;
import beans.InventoryBean;
import beans.SetBean;
import db.DBUtil;

/**
 *
 * @author  __USER__
 */
//板棍取出
public class createStuffQuitInterFacen extends javax.swing.JPanel {
	TableModel m1 = null;
	/** Creates new form createUserStuffInterFacen */
	public createStuffQuitInterFacen(String name) {
		initComponents(name);
		this.setBackground(java.awt.Color.cyan);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents(final String name) {
		Connection con = null;
		PreparedStatement prs = null;
		ResultSet rs = null;
		Object[][] data = null;
		StringBuffer[][] shuzu= new StringBuffer[13][10] ;
		Object[] mc;
		JTable ta1 ;
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jTextField5 = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jTextField6 = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		jTextField7 = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();
		jLabel8 = new javax.swing.JLabel();
		jTextField8 = new javax.swing.JTextField();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		SetBean s=new SetBean();
		s.setName("scantime");
		SetDAOinf sd=new SetDAOimpl();
		SetBean sb=new SetBean();
		sb=sd.select(s);
		final int mintime=Integer.parseInt(sb.getValue().trim());
		jPanel1.setBackground(Color.CYAN);
		jPanel2.setBackground(Color.CYAN);
		jLabel1.setText("\u5e93\u4f4d\u53f7\u7801");

		jButton1.setText("\u677f\u68cd\u4fe1\u606f");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				InventoryBean ib=new InventoryBean();
				ib.setLocation(jTextField1.getText());
				InventoryBeanDAOinf ibd=new InventoryBeanDAOimpl();
				InventoryBean ibb=new InventoryBean();
				ibb=ibd.selectalln(ib);
				if(ibb!=null){
					jTextField2.setText(ibb.getPlate_name());
					jTextField3.setText(ibb.getPlate_id());
					jTextField4.setText(ibb.getColor());
					jTextField5.setText(ibb.getColor_num());
					jTextField6.setText(ibb.getAmout()+"");
					jTextField7.setText("0");
				}else{
					JOptionPane.showMessageDialog(null, "库位号不存在或没有板棍放置");
				}
			}
		});
		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jLabel2.setText("\u5370\u7248\u540d\u79f0");

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jLabel3.setText("\u5370\u7248\u7248\u53f7");

		jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jLabel5.setText("    \u8272\u522b");

		jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jLabel4.setText("    \u8272\u5e8f");

		jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jLabel6.setText("    \u91d1\u989d");

		jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jLabel7.setText("    印数");

		jButton2.setText("自动取版");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				//ib用于更新存储信息，as用于增加存储记录
				InventoryBean ib=new InventoryBean();
				AccessBean as=new AccessBean();
				ib.setLocation(jTextField1.getText());
				as.setLocation(jTextField1.getText());
				as.setPlate_name(jTextField2.getText());
				as.setPlate_id(jTextField3.getText());
				Date d=new Date();
				Timestamp t=new Timestamp(d.getTime());
				as.setDateTime(t);
				as.setAdmin_name(name);
				as.setPrint_num(Integer.parseInt(jTextField7.getText()));
				as.setStatus("取出");
				AccessDAOinf ad=new AccessDAOImpl();
				InventoryBeanDAOinf ibd=new InventoryBeanDAOimpl();
				InventoryBean ibb=new InventoryBean();
				ibb=ibd.selectalln(ib);
				
				
				String msg=jTextField1.getText();
				int m=-1;//确定几号小车
				int n=-1;//确定左右
				String c=msg.substring(4, 6);
				switch(c){
				case "01":
					m=1;
					n=0;
					break;
				case "02":
					m=1;
					n=1;
					break;
				case "03":
					m=2;
					n=0;
					break;
				case "04":
					m=2;
					n=1;
					break;
				case "05":
					m=3;
					n=0;
					break;
				case "06":
					m=3;
					n=1;
					break;
				case "07":
					m=4;
					n=0;
					break;
				case "08":
					m=4;
					n=1;
					break;
				case "09":
					m=5;
					n=0;
					break;
				case "10":
					m=5;
					n=1;
					break;
				}
				
				if(ibd.isout(ib)){
					JOptionPane.showMessageDialog(null, "取出失败，该位置不存在板棍");
				
				}else if(My_MainFrame.d[m*2-2][4]==1&&My_MainFrame.d[m*2-2][2]==0){//条件判断小车位置
					My_MainFrame.a[m*2-1][2]=1;
					My_MainFrame.a[m*2-1][4]=ibb.getRow();
					My_MainFrame.a[m*2-1][5]=ibb.getCol();
					My_MainFrame.a[m*2-1][6]=n;
					JOptionPane.showMessageDialog(null, "正在取版");
					int A1=0;
					long ptime=System.currentTimeMillis();
					while(true){
						Date dNow = new Date();   //当前时间
						int s=dNow.getSeconds();
						if(s%2==1){
							if(A1==0){
							A1=1;
							if(My_MainFrame.d[m*2-2][0]==1){
								My_MainFrame.a[m*2-1][2]=0;
								if(ibd.StuffOut(ib)&&ad.StuffInterRecord(as)){
									JOptionPane.showMessageDialog(null, "取版完成");
								}else{
									JOptionPane.showMessageDialog(null, "取版完成但数据没有更新");
								}
								break;
							}else if(System.currentTimeMillis()-ptime>=60000*mintime){
								JOptionPane.showMessageDialog(null, "取版失败，请检查机器");
								My_MainFrame.a[m*2-2][2]=0;
								break;
							}
							}
						}else{
							A1=0;
						}
					}
					
				}else{
					JOptionPane.showMessageDialog(null, "请先将"+m+"号小车出库并保证卡爪无版");
				}
			}
		});
		jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jLabel8.setText("\u67e5\u8be2\u67b6\u53f7");

		jButton3.setText("\u67e5\u8be2");

		jButton4.setText("手动取版");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				InventoryBean ib=new InventoryBean();
				AccessBean as=new AccessBean();
				ib.setLocation(jTextField1.getText());
				ib.setPlate_id(jTextField3.getText());
				as.setLocation(jTextField1.getText());
				as.setPlate_name(jTextField2.getText());
				as.setPlate_id(jTextField3.getText());
				Date d=new Date();
				Timestamp t=new Timestamp(d.getTime());
				as.setDateTime(t);
				as.setAdmin_name(name);
				as.setPrint_num(Integer.parseInt(jTextField7.getText()));
				as.setStatus("取出");
				AccessDAOinf ad=new AccessDAOImpl();
				InventoryBeanDAOinf ibd=new InventoryBeanDAOimpl();
				if(ibd.isout(ib)){
					JOptionPane.showMessageDialog(null, "取版失败，该位置没有板棍");
				}else{
					if(ibd.StuffOut(ib)&&ad.StuffInterRecord(as)){
						JOptionPane.showMessageDialog(null, "取出成功");
					}else{
						JOptionPane.showMessageDialog(null, "取出失败");
					}
				}
				
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(231,
																				231,
																				231)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addGroup(
																								jPanel1Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																										.addGroup(
																												jPanel1Layout
																														.createSequentialGroup()
																														.addGap(59,
																																59,
																																59)
																														.addComponent(
																																jLabel2,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																64,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addPreferredGap(
																																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																														.addComponent(
																																jTextField2,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																103,
																																javax.swing.GroupLayout.PREFERRED_SIZE))
																										.addGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING,
																												jPanel1Layout
																														.createSequentialGroup()
																														.addGroup(
																																jPanel1Layout
																																		.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.TRAILING)
																																		.addComponent(
																																				jLabel6,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				64,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addComponent(
																																				jLabel5,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				64,
																																				javax.swing.GroupLayout.PREFERRED_SIZE))
																														.addPreferredGap(
																																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																														.addGroup(
																																jPanel1Layout
																																		.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																		.addComponent(
																																				jTextField6,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				103,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addComponent(
																																				jTextField4,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				103,
																																				javax.swing.GroupLayout.PREFERRED_SIZE))))
																						.addComponent(
																								jLabel1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								64,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(110,
																				110,
																				110)
																		.addComponent(
																				jLabel8,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				64,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextField8,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				103,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				jButton3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				69,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(10,
																				10,
																				10)
																		.addComponent(
																				jTextField1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				103,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(44,
																				44,
																				44)
																		.addComponent(
																				jButton2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				102,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(26, 26, 26)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel4,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				64,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextField5,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				103,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel7,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				64,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextField7,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				103,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jButton1)
																						.addComponent(
																								jLabel3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								64,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextField3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				103,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(
																jButton4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																102,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(558, 558, 558)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jButton1)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																27,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jTextField2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								27,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jTextField3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								27,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jTextField4,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel5,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								27,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jTextField5,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel4,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								27,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jTextField6,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel6,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								27,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jTextField7,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel7,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								27,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addContainerGap(
																				59,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jButton2)
																						.addComponent(
																								jLabel8,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								27,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jTextField8,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton3)
																						.addComponent(
																								jButton4))
																		.addContainerGap()))));

		int a1,a2,a3;
		mc = new Object[] { " ","第一列", "第二列", "第三列", "第四列", "第五列"
				, "第六列", "第七列" , "第八列" , "第九列" , "第十列"  };
		m1 = new DefaultTableModel(data,mc){
			public boolean isCellEditable(int rowIndex, int columnIndex) {   
			     return false;
			}} ;
		ta1=new JTable(m1);
		ta1.setBackground(Color.cyan);
		ta1.setRowHeight(25);
		con=DBUtil.getConn();
		for(int i=0;i<13;i++){
			for(int j=0;j<10;j++){
				shuzu[i][j]=new StringBuffer("");
			}
		}
			
		try {
			String sql="select * from inventory_list where Frame_num=1";
			prs=con.prepareStatement(sql);
			rs=prs.executeQuery();
			
			while(rs.next()){
				a1=Integer.parseInt(rs.getString("Row"));
				a2=Integer.parseInt(rs.getString("Col"));
				a3=Integer.parseInt(rs.getString("Status"));	
				if(a3==1)
				shuzu[a2-1][a1-1].append("在库");
				else if(a3==0)
					shuzu[a2-1][a1-1].append("不在");
				else
					shuzu[a2-1][a1-1].append("");
				};
				for(int i=0;i<13;i++){
					for(int j=0;j<10;j++){
						if(i<9){
							if(j<9){
								shuzu[i][j].append("(0"+(j+1)+"0"+(i+1)+"01)");	
							}else{
								shuzu[i][j].append("("+(j+1)+"0"+(i+1)+"01)");
							}
						}else{
							if(j<9){
								shuzu[i][j].append("(0"+(j+1)+""+(i+1)+"01)");
							}else{
								shuzu[i][j].append("("+(j+1)+""+(i+1)+"01)");
							}
						}
					}
				}
				String[] rowValues={"第一层",shuzu[0][0].toString(),shuzu[0][1].toString(),shuzu[0][2].toString(),shuzu[0][3].toString(),
						shuzu[0][4].toString(),shuzu[0][5].toString(),shuzu[0][6].toString(),shuzu[0][7].toString(),shuzu[0][8].toString().toString(),shuzu[0][9].toString()};
				((DefaultTableModel) m1).addRow(rowValues);
				String[] rowValues1={"第二层",shuzu[1][0].toString(),shuzu[1][1].toString(),shuzu[1][2].toString(),shuzu[1][3].toString(),
						shuzu[1][4].toString(),shuzu[1][5].toString(),shuzu[1][6].toString(),shuzu[1][7].toString(),shuzu[1][8].toString(),shuzu[1][9].toString()};
				((DefaultTableModel) m1).addRow(rowValues1);
				String[] rowValues2={"第三层",shuzu[2][0].toString(),shuzu[2][1].toString(),shuzu[2][2].toString(),shuzu[2][3].toString(),
						shuzu[2][4].toString(),shuzu[2][5].toString(),shuzu[2][6].toString(),shuzu[2][7].toString(),shuzu[2][8].toString(),shuzu[2][9].toString()};
				((DefaultTableModel) m1).addRow(rowValues2);
				String[] rowValues3={"第四层",shuzu[3][0].toString(),shuzu[3][1].toString(),shuzu[3][2].toString(),shuzu[3][3].toString(),
						shuzu[3][4].toString(),shuzu[3][5].toString(),shuzu[3][6].toString(),shuzu[3][7].toString(),shuzu[3][8].toString(),shuzu[3][9].toString()};
				((DefaultTableModel) m1).addRow(rowValues3);
				String[] rowValues4={"第五层",shuzu[4][0].toString(),shuzu[4][1].toString(),shuzu[4][2].toString(),shuzu[4][3].toString(),
						shuzu[4][4].toString(),shuzu[4][5].toString(),shuzu[4][6].toString(),shuzu[4][7].toString(),shuzu[4][8].toString(),shuzu[4][9].toString()};
				((DefaultTableModel) m1).addRow(rowValues4);
				String[] rowValues5={"第六层",shuzu[5][0].toString(),shuzu[5][1].toString(),shuzu[5][2].toString(),shuzu[5][3].toString(),
						shuzu[5][4].toString(),shuzu[5][5].toString(),shuzu[5][6].toString(),shuzu[5][7].toString(),shuzu[5][8].toString(),shuzu[5][9].toString()};
				((DefaultTableModel) m1).addRow(rowValues5);
				String[] rowValues6={"第七层",shuzu[6][0].toString(),shuzu[6][1].toString(),shuzu[6][2].toString(),shuzu[6][3].toString(),
						shuzu[6][4].toString(),shuzu[6][5].toString(),shuzu[6][6].toString(),shuzu[6][7].toString(),shuzu[6][8].toString(),shuzu[6][9].toString()};
				((DefaultTableModel) m1).addRow(rowValues6);
				String[] rowValues7={"第八层",shuzu[7][0].toString(),shuzu[7][1].toString(),shuzu[7][2].toString(),shuzu[7][3].toString(),
						shuzu[7][4].toString(),shuzu[7][5].toString(),shuzu[7][6].toString(),shuzu[7][7].toString(),shuzu[7][8].toString(),shuzu[7][9].toString()};
				((DefaultTableModel) m1).addRow(rowValues7);
				String[] rowValues8={"第九层",shuzu[8][0].toString(),shuzu[8][1].toString(),shuzu[8][2].toString(),shuzu[8][3].toString(),
						shuzu[0][4].toString(),shuzu[8][5].toString(),shuzu[8][6].toString(),shuzu[8][7].toString(),shuzu[8][8].toString(),shuzu[8][9].toString()};
				((DefaultTableModel) m1).addRow(rowValues8);
				String[] rowValues9={"第十层",shuzu[9][0].toString(),shuzu[9][1].toString(),shuzu[9][2].toString(),shuzu[9][3].toString(),
						shuzu[9][4].toString(),shuzu[9][5].toString(),shuzu[9][6].toString(),shuzu[9][7].toString(),shuzu[9][8].toString(),shuzu[9][9].toString()};
				((DefaultTableModel) m1).addRow(rowValues9);
				String[] rowValues10={"第十一层",shuzu[10][0].toString(),shuzu[10][1].toString(),shuzu[10][2].toString(),shuzu[10][3].toString(),
						shuzu[10][4].toString(),shuzu[10][5].toString(),shuzu[10][6].toString(),shuzu[10][7].toString(),shuzu[10][8].toString(),shuzu[10][9].toString()};
				((DefaultTableModel) m1).addRow(rowValues10);
				String[] rowValues11={"第十二层",shuzu[11][0].toString(),shuzu[11][1].toString(),shuzu[10][2].toString(),shuzu[11][3].toString(),
						shuzu[11][4].toString(),shuzu[11][5].toString(),shuzu[11][6].toString(),shuzu[11][7].toString(),shuzu[11][8].toString(),shuzu[11][9].toString()};
				((DefaultTableModel) m1).addRow(rowValues11);
				String[] rowValues12={"第十三层",shuzu[12][0].toString(),shuzu[12][1].toString(),shuzu[12][2].toString(),shuzu[12][3].toString(),
						shuzu[12][4].toString(),shuzu[12][5].toString(),shuzu[12][6].toString(),shuzu[12][7].toString(),shuzu[12][8].toString(),shuzu[12][9].toString()};
				((DefaultTableModel) m1).addRow(rowValues12);
			   
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	     
		jScrollPane1.setViewportView(ta1);
		jScrollPane1.setBackground(Color.cyan);
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				PreparedStatement prs=null;
				Connection con = null;
				ResultSet rs = null;
				int a1,a2,a3;
				JTable ta1;
				StringBuffer[][] shuzu= new StringBuffer[13][10] ;
				Object[] mc;
				Object[][] data = null;
				int n=1;
				try{
					 n=Integer.parseInt(jTextField8.getText());
				}catch (NumberFormatException e) {
					// TODO: handle exception
					JOptionPane.showMessageDialog(null, "请输入正确的架位号");
				}
				mc = new Object[] { " ","第一列", "第二列", "第三列", "第四列", "第五列"
						, "第六列", "第七列" , "第八列" , "第九列" , "第十列"  };
				m1 = new DefaultTableModel(data,mc){
					public boolean isCellEditable(int rowIndex, int columnIndex) {   
					     return false;
					}} ;
				ta1=new JTable(m1);
				ta1.setBackground(Color.cyan);
				ta1.setRowHeight(25);
				con=DBUtil.getConn();
				for(int i=0;i<13;i++){
					for(int j=0;j<10;j++){
						shuzu[i][j]=new StringBuffer("");
					}
				}
				String m=null;
				try {
					String sql="select * from inventory_list where Frame_num="+n+"";
					prs=con.prepareStatement(sql);
					rs=prs.executeQuery();
					if(n<10){
						m="0"+n;
					}else{
						m=n+"";
					}
					while(rs.next()){
						a1=Integer.parseInt(rs.getString("Row"));
						a2=Integer.parseInt(rs.getString("Col"));
						a3=Integer.parseInt(rs.getString("Status"));	
						if(a3==1)
							shuzu[a2-1][a1-1].append("在库");
							else if(a3==0)
								shuzu[a2-1][a1-1].append("不在");
							else
								shuzu[a2-1][a1-1].append("");
							};
							for(int i=0;i<13;i++){
								for(int j=0;j<10;j++){
									if(i<9){
										if(j<9){
											shuzu[i][j].append("(0"+(j+1)+"0"+(i+1)+""+m+")");	
										}else{
											shuzu[i][j].append("("+(j+1)+"0"+(i+1)+""+m+")");
										}
									}else{
										if(j<9){
											shuzu[i][j].append("(0"+(j+1)+""+(i+1)+""+m+")");
										}else{
											shuzu[i][j].append("("+(j+1)+""+(i+1)+""+m+")");
										}
									}
								}
							}
							String[] rowValues={"第一层",shuzu[0][0].toString(),shuzu[0][1].toString(),shuzu[0][2].toString(),shuzu[0][3].toString(),
									shuzu[0][4].toString(),shuzu[0][5].toString(),shuzu[0][6].toString(),shuzu[0][7].toString(),shuzu[0][8].toString().toString(),shuzu[0][9].toString()};
							((DefaultTableModel) m1).addRow(rowValues);
							String[] rowValues1={"第二层",shuzu[1][0].toString(),shuzu[1][1].toString(),shuzu[1][2].toString(),shuzu[1][3].toString(),
									shuzu[1][4].toString(),shuzu[1][5].toString(),shuzu[1][6].toString(),shuzu[1][7].toString(),shuzu[1][8].toString(),shuzu[1][9].toString()};
							((DefaultTableModel) m1).addRow(rowValues1);
							String[] rowValues2={"第三层",shuzu[2][0].toString(),shuzu[2][1].toString(),shuzu[2][2].toString(),shuzu[2][3].toString(),
									shuzu[2][4].toString(),shuzu[2][5].toString(),shuzu[2][6].toString(),shuzu[2][7].toString(),shuzu[2][8].toString(),shuzu[2][9].toString()};
							((DefaultTableModel) m1).addRow(rowValues2);
							String[] rowValues3={"第四层",shuzu[3][0].toString(),shuzu[3][1].toString(),shuzu[3][2].toString(),shuzu[3][3].toString(),
									shuzu[3][4].toString(),shuzu[3][5].toString(),shuzu[3][6].toString(),shuzu[3][7].toString(),shuzu[3][8].toString(),shuzu[3][9].toString()};
							((DefaultTableModel) m1).addRow(rowValues3);
							String[] rowValues4={"第五层",shuzu[4][0].toString(),shuzu[4][1].toString(),shuzu[4][2].toString(),shuzu[4][3].toString(),
									shuzu[4][4].toString(),shuzu[4][5].toString(),shuzu[4][6].toString(),shuzu[4][7].toString(),shuzu[4][8].toString(),shuzu[4][9].toString()};
							((DefaultTableModel) m1).addRow(rowValues4);
							String[] rowValues5={"第六层",shuzu[5][0].toString(),shuzu[5][1].toString(),shuzu[5][2].toString(),shuzu[5][3].toString(),
									shuzu[5][4].toString(),shuzu[5][5].toString(),shuzu[5][6].toString(),shuzu[5][7].toString(),shuzu[5][8].toString(),shuzu[5][9].toString()};
							((DefaultTableModel) m1).addRow(rowValues5);
							String[] rowValues6={"第七层",shuzu[6][0].toString(),shuzu[6][1].toString(),shuzu[6][2].toString(),shuzu[6][3].toString(),
									shuzu[6][4].toString(),shuzu[6][5].toString(),shuzu[6][6].toString(),shuzu[6][7].toString(),shuzu[6][8].toString(),shuzu[6][9].toString()};
							((DefaultTableModel) m1).addRow(rowValues6);
							String[] rowValues7={"第八层",shuzu[7][0].toString(),shuzu[7][1].toString(),shuzu[7][2].toString(),shuzu[7][3].toString(),
									shuzu[7][4].toString(),shuzu[7][5].toString(),shuzu[7][6].toString(),shuzu[7][7].toString(),shuzu[7][8].toString(),shuzu[7][9].toString()};
							((DefaultTableModel) m1).addRow(rowValues7);
							String[] rowValues8={"第九层",shuzu[8][0].toString(),shuzu[8][1].toString(),shuzu[8][2].toString(),shuzu[8][3].toString(),
									shuzu[0][4].toString(),shuzu[8][5].toString(),shuzu[8][6].toString(),shuzu[8][7].toString(),shuzu[8][8].toString(),shuzu[8][9].toString()};
							((DefaultTableModel) m1).addRow(rowValues8);
							String[] rowValues9={"第十层",shuzu[9][0].toString(),shuzu[9][1].toString(),shuzu[9][2].toString(),shuzu[9][3].toString(),
									shuzu[9][4].toString(),shuzu[9][5].toString(),shuzu[9][6].toString(),shuzu[9][7].toString(),shuzu[9][8].toString(),shuzu[9][9].toString()};
							((DefaultTableModel) m1).addRow(rowValues9);
							String[] rowValues10={"第十一层",shuzu[10][0].toString(),shuzu[10][1].toString(),shuzu[10][2].toString(),shuzu[10][3].toString(),
									shuzu[10][4].toString(),shuzu[10][5].toString(),shuzu[10][6].toString(),shuzu[10][7].toString(),shuzu[10][8].toString(),shuzu[10][9].toString()};
							((DefaultTableModel) m1).addRow(rowValues10);
							String[] rowValues11={"第十二层",shuzu[11][0].toString(),shuzu[11][1].toString(),shuzu[10][2].toString(),shuzu[11][3].toString(),
									shuzu[11][4].toString(),shuzu[11][5].toString(),shuzu[11][6].toString(),shuzu[11][7].toString(),shuzu[11][8].toString(),shuzu[11][9].toString()};
							((DefaultTableModel) m1).addRow(rowValues11);
							String[] rowValues12={"第十三层",shuzu[12][0].toString(),shuzu[12][1].toString(),shuzu[12][2].toString(),shuzu[12][3].toString(),
									shuzu[12][4].toString(),shuzu[12][5].toString(),shuzu[12][6].toString(),shuzu[12][7].toString(),shuzu[12][8].toString(),shuzu[12][9].toString()};
							((DefaultTableModel) m1).addRow(rowValues12);
					   
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			
				jScrollPane1.setViewportView(ta1);
				jScrollPane1.setBackground(Color.cyan);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout
						.createSequentialGroup()
						.addContainerGap()
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 928,
								Short.MAX_VALUE).addContainerGap()));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout
						.createSequentialGroup()
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								350,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1,
						javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE, 1383,
						Short.MAX_VALUE)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(89, 89, 89)
								.addComponent(jPanel2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(342, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(210, Short.MAX_VALUE)));
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextField7;
	private javax.swing.JTextField jTextField8;
	// End of variables declaration//GEN-END:variables

}