/*
 * createOutInFace.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.Color;
import java.util.Date;

import javax.swing.JButton;
import javax.swing.JOptionPane;

import beans.SetBean;

import daos.ExcelDAOimpl;
import daos.ExcelDAOinf;
import daos.SetDAOimpl;
import daos.SetDAOinf;

/**
 *
 * @author  __USER__
 */
public class createOutInFace extends javax.swing.JPanel {
	/** Creates new form createOutInFace */
	public createOutInFace() {
		initComponents();
		this.setBackground(java.awt.Color.cyan);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	
	private void initComponents() {
		    My_MainFrame.b++;
			jLabel1 = new javax.swing.JLabel();
			jPanel1 = new javax.swing.JPanel();
			jTextField1 = new javax.swing.JTextField();
			jLabel2 = new javax.swing.JLabel();
			jButton1 = new javax.swing.JButton();
			
			jLabel3 = new javax.swing.JLabel();
			jLabel4 = new javax.swing.JLabel();
			jLabel5 = new javax.swing.JLabel();
			jLabel6 = new javax.swing.JLabel();
			jTextField2 = new javax.swing.JTextField();
			jTextField3 = new javax.swing.JTextField();
			jTextField4 = new javax.swing.JTextField();
			jTextField5 = new javax.swing.JTextField();
			jButton3 = new javax.swing.JButton();
			jButton10 = new javax.swing.JButton();
			jButton8 = new javax.swing.JButton();
			jButton6 = new javax.swing.JButton();
			jButton4 = new javax.swing.JButton();
			jButton2 = new javax.swing.JButton();
			jButton9 = new javax.swing.JButton();
			jButton5 = new javax.swing.JButton();
			jButton7 = new javax.swing.JButton();
			jPanel1.setBackground(Color.CYAN);
			jTextField1.setEditable(false);
			jTextField2.setEditable(false);
			jTextField3.setEditable(false);
			jTextField4.setEditable(false);
			jTextField5.setEditable(false);
			jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
			jLabel1.setText("\u51fa\u5e93\u5165\u5e93");
			jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
			jLabel2.setText("1\u53f7\u5c0f\u8f66\uff1a");
			jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
			jButton1.setText("\u51fa\u5e93");
			jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
			jLabel3.setText("5\u53f7\u5c0f\u8f66\uff1a");
			jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
			jLabel4.setText("2\u53f7\u5c0f\u8f66\uff1a");
			jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
			jLabel5.setText("4\u53f7\u5c0f\u8f66\uff1a");
			jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
			jLabel6.setText("3\u53f7\u5c0f\u8f66\uff1a");
			jButton3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
			jButton3.setText("\u51fa\u5e93");
			SetBean s=new SetBean();
			s.setName("inouttime");
			SetDAOinf sd=new SetDAOimpl();
			SetBean sb=new SetBean();
			sb=sd.select(s);
			final int mintime=Integer.parseInt(sb.getValue().trim());
			if(My_MainFrame.b==1){
				Thread thread=new Thread(new MyThred());
				thread.start();
			}
			jButton1.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
							My_MainFrame.a[1][0]=1;
							JOptionPane.showMessageDialog(null, "正在出库");
							int A1=0;
							long ptime=System.currentTimeMillis();
							while(true){
								Date dNow = new Date();   //当前时间
								int s=dNow.getSeconds();
								if(s%2==1){
									if(A1==0){
									A1=1;
									if(My_MainFrame.d[0][4]==1){
										My_MainFrame.a[1][0]=0;
										JOptionPane.showMessageDialog(null, "出库完成");
										break;
									}else if(System.currentTimeMillis()-ptime>=60000*mintime){
										JOptionPane.showMessageDialog(null, "出库 失败，请检查机器");
										My_MainFrame.a[1][0]=0;
										break;
									}
									}
								}else{
									A1=0;
									
								}
							}
				}
			});
			jButton3.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					My_MainFrame.a[3][0]=1;
					JOptionPane.showMessageDialog(null, "正在出库");
					int A1=0;
					long ptime=System.currentTimeMillis();
					while(true){
						Date dNow = new Date();   //当前时间
						int s=dNow.getSeconds();
						if(s%2==1){
							if(A1==0){
							A1=1;
							if(My_MainFrame.d[2][4]==1){
								JOptionPane.showMessageDialog(null, "出库完成");
								My_MainFrame.a[3][0]=0;
								break;
							}else if(System.currentTimeMillis()-ptime>=60000*mintime){
								JOptionPane.showMessageDialog(null, "出库 失败，请检查机器");
								My_MainFrame.a[3][0]=0;
								break;
							}
							}
						}else{
							A1=0;
							
						}
					}
		
				}
			});
			jButton10.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
			jButton10.setText("\u5165\u5e93");
			jButton10.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {


					My_MainFrame.a[9][1]=1;
					JOptionPane.showMessageDialog(null, "正在入库");
					int A1=0;
					long ptime=System.currentTimeMillis();
					while(true){
						Date dNow = new Date();   //当前时间
						int s=dNow.getSeconds();
						if(s%2==1){
							if(A1==0){
							A1=1;
							if(My_MainFrame.d[8][4]==0){
								JOptionPane.showMessageDialog(null, "入库完成");
								My_MainFrame.a[9][1]=0;
								break;
							}else if(System.currentTimeMillis()-ptime>=60000*mintime){
								JOptionPane.showMessageDialog(null, "入库 失败，请检查机器");
								My_MainFrame.a[9][1]=0;
								break;
							}
							}
						}else{
							A1=0;
							
						}
					}
		
				
				}
			});
			jButton8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
			jButton8.setText("\u5165\u5e93");
			jButton8.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {


					My_MainFrame.a[7][1]=1;
					JOptionPane.showMessageDialog(null, "正在入库");
					int A1=0;
					long ptime=System.currentTimeMillis();
					while(true){
						Date dNow = new Date();   //当前时间
						int s=dNow.getSeconds();
						if(s%2==1){
							if(A1==0){
							A1=1;
							if(My_MainFrame.d[6][4]==0){
								JOptionPane.showMessageDialog(null, "入库完成");
								My_MainFrame.a[7][1]=0;
								break;
							}else if(System.currentTimeMillis()-ptime>=60000*mintime){
								JOptionPane.showMessageDialog(null, "入库 失败，请检查机器");
								My_MainFrame.a[7][1]=0;
								break;
							}
							}
						}else{
							A1=0;
							
						}
					}
		
				
				}
			});
			jButton6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
			jButton6.setText("\u5165\u5e93");
			jButton6.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {


					My_MainFrame.a[5][1]=1;
					JOptionPane.showMessageDialog(null, "正在入库");
					int A1=0;
					long ptime=System.currentTimeMillis();
					while(true){
						Date dNow = new Date();   //当前时间
						int s=dNow.getSeconds();
						if(s%2==1){
							if(A1==0){
							A1=1;
							if(My_MainFrame.d[4][4]==0){
								JOptionPane.showMessageDialog(null, "入库完成");
								My_MainFrame.a[5][1]=0;
								break;
							}else if(System.currentTimeMillis()-ptime>=60000*mintime){
								JOptionPane.showMessageDialog(null, "入库 失败，请检查机器");
								My_MainFrame.a[7][1]=0;
								break;
							}
							}
						}else{
							A1=0;
							
						}
					}
		
				
				}
			});
			jButton4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
			jButton4.setText("\u5165\u5e93");
			jButton4.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {


					My_MainFrame.a[3][1]=1;
					JOptionPane.showMessageDialog(null, "正在入库");
					int A1=0;
					long ptime=System.currentTimeMillis();
					while(true){
						Date dNow = new Date();   //当前时间
						int s=dNow.getSeconds();
						if(s%2==1){
							if(A1==0){
							A1=1;
							if(My_MainFrame.d[2][4]==0){
								JOptionPane.showMessageDialog(null, "入库完成");
								My_MainFrame.a[3][1]=0;
								break;
							}else if(System.currentTimeMillis()-ptime>=60000*mintime){
								JOptionPane.showMessageDialog(null, "入库 失败，请检查机器");
								My_MainFrame.a[3][1]=0;
								break;
							}
							}
						}else{
							A1=0;
							
						}
					}
		
				
				}
			});
			jButton2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
			jButton2.setText("\u5165\u5e93");
			jButton2.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					My_MainFrame.a[1][1]=1;
					JOptionPane.showMessageDialog(null, "正在入库");
					int A1=0;
					long ptime=System.currentTimeMillis();
					while(true){
						Date dNow = new Date();   //当前时间
						int s=dNow.getSeconds();
						if(s%2==1){
							if(A1==0){
							A1=1;
							if(My_MainFrame.d[0][4]==0){
								My_MainFrame.a[1][1]=0;
								JOptionPane.showMessageDialog(null, "入库完成");
								break;
							}else if(System.currentTimeMillis()-ptime>=60000*mintime){
								JOptionPane.showMessageDialog(null, "入库 失败，请检查机器");
								My_MainFrame.a[1][1]=0;
								break;
							}
							}
						}else{
							A1=0;
							
						}
					}
		
				}
			});
			jButton9.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
			jButton9.setText("\u51fa\u5e93");
			jButton9.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {

					My_MainFrame.a[9][0]=1;
					JOptionPane.showMessageDialog(null, "正在出库");
					int A1=0;
					long ptime=System.currentTimeMillis();
					while(true){
						Date dNow = new Date();   //当前时间
						int s=dNow.getSeconds();
						if(s%2==1){
							if(A1==0){
							A1=1;
							if(My_MainFrame.d[8][4]==1){
								My_MainFrame.a[9][0]=0;
								JOptionPane.showMessageDialog(null, "出库完成");
								break;
							}else if(System.currentTimeMillis()-ptime>=60000*mintime){
								JOptionPane.showMessageDialog(null, "出库 失败，请检查机器");
								My_MainFrame.a[9][0]=0;
								break;
							}
							}
						}else{
							A1=0;
							
						}
					}
		
				}
			});
			jButton5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
			jButton5.setText("\u51fa\u5e93");
			jButton5.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {

					My_MainFrame.a[5][0]=1;
					JOptionPane.showMessageDialog(null, "正在出库");
					int A1=0;
					long ptime=System.currentTimeMillis();
					while(true){
						Date dNow = new Date();   //当前时间
						int s=dNow.getSeconds();
						if(s%2==1){
							if(A1==0){
							A1=1;
							if(My_MainFrame.d[4][4]==1){
								My_MainFrame.a[5][0]=0;
								JOptionPane.showMessageDialog(null, "出库完成");
								break;
							}else if(System.currentTimeMillis()-ptime>=60000*mintime){
								JOptionPane.showMessageDialog(null, "出库 失败，请检查机器");
								My_MainFrame.a[5][0]=0;
								break;
							}
							}
						}else{
							A1=0;
							
						}
					}
		
				}
			});
			jButton7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
			jButton7.setText("\u51fa\u5e93");
			jButton7.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {

					My_MainFrame.a[7][0]=1;
					JOptionPane.showMessageDialog(null, "正在出库");
					int A1=0;
					long ptime=System.currentTimeMillis();
					while(true){
						Date dNow = new Date();   //当前时间
						int s=dNow.getSeconds();
						if(s%2==1){
							if(A1==0){
							A1=1;
							if(My_MainFrame.d[6][4]==1){
								My_MainFrame.a[7][0]=0;
								JOptionPane.showMessageDialog(null, "出库完成");
								break;
							}else if(System.currentTimeMillis()-ptime>=60000*mintime){
								JOptionPane.showMessageDialog(null, "出库 失败，请检查机器");
								My_MainFrame.a[7][0]=0;
								break;
							}
							}
						}else{
							A1=0;
							
						}
					}
		
				}
			});
			javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
					jPanel1);
			jPanel1.setLayout(jPanel1Layout);
			jPanel1Layout
					.setHorizontalGroup(jPanel1Layout
							.createParallelGroup(
									javax.swing.GroupLayout.Alignment.LEADING)
							.addGroup(
									jPanel1Layout
											.createSequentialGroup()
											.addGap(109, 109, 109)
											.addGroup(
													jPanel1Layout
															.createParallelGroup(
																	javax.swing.GroupLayout.Alignment.LEADING)
															.addGroup(
																	jPanel1Layout
																			.createSequentialGroup()
																			.addComponent(
																					jLabel2)
																			.addPreferredGap(
																					javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																			.addComponent(
																					jTextField1,
																					javax.swing.GroupLayout.PREFERRED_SIZE,
																					84,
																					javax.swing.GroupLayout.PREFERRED_SIZE))
															.addGroup(
																	jPanel1Layout
																			.createSequentialGroup()
																			.addComponent(
																					jLabel4)
																			.addPreferredGap(
																					javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																			.addComponent(
																					jTextField2,
																					javax.swing.GroupLayout.PREFERRED_SIZE,
																					84,
																					javax.swing.GroupLayout.PREFERRED_SIZE))
															.addGroup(
																	jPanel1Layout
																			.createSequentialGroup()
																			.addComponent(
																					jLabel6)
																			.addPreferredGap(
																					javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																			.addComponent(
																					jTextField3,
																					javax.swing.GroupLayout.PREFERRED_SIZE,
																					84,
																					javax.swing.GroupLayout.PREFERRED_SIZE))
															.addGroup(
																	jPanel1Layout
																			.createSequentialGroup()
																			.addComponent(
																					jLabel5)
																			.addPreferredGap(
																					javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																			.addComponent(
																					jTextField4,
																					javax.swing.GroupLayout.PREFERRED_SIZE,
																					84,
																					javax.swing.GroupLayout.PREFERRED_SIZE))
															.addGroup(
																	jPanel1Layout
																			.createSequentialGroup()
																			.addComponent(
																					jLabel3)
																			.addPreferredGap(
																					javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																			.addComponent(
																					jTextField5,
																					javax.swing.GroupLayout.PREFERRED_SIZE,
																					84,
																					javax.swing.GroupLayout.PREFERRED_SIZE)))
											.addGroup(
													jPanel1Layout
															.createParallelGroup(
																	javax.swing.GroupLayout.Alignment.TRAILING)
															.addGroup(
																	jPanel1Layout
																			.createSequentialGroup()
																			.addPreferredGap(
																					javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																			.addComponent(
																					jButton9))
															.addGroup(
																	javax.swing.GroupLayout.Alignment.LEADING,
																	jPanel1Layout
																			.createParallelGroup(
																					javax.swing.GroupLayout.Alignment.TRAILING)
																			.addGroup(
																					jPanel1Layout
																							.createSequentialGroup()
																							.addPreferredGap(
																									javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																							.addComponent(
																									jButton7))
																			.addGroup(
																					javax.swing.GroupLayout.Alignment.LEADING,
																					jPanel1Layout
																							.createParallelGroup(
																									javax.swing.GroupLayout.Alignment.TRAILING)
																							.addGroup(
																									jPanel1Layout
																											.createSequentialGroup()
																											.addPreferredGap(
																													javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																											.addComponent(
																													jButton5))
																							.addGroup(
																									javax.swing.GroupLayout.Alignment.LEADING,
																									jPanel1Layout
																											.createParallelGroup(
																													javax.swing.GroupLayout.Alignment.TRAILING)
																											.addGroup(
																													jPanel1Layout
																															.createSequentialGroup()
																															.addPreferredGap(
																																	javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																															.addComponent(
																																	jButton3))
																											.addGroup(
																													javax.swing.GroupLayout.Alignment.LEADING,
																													jPanel1Layout
																															.createSequentialGroup()
																															.addPreferredGap(
																																	javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																																	150,
																																	Short.MAX_VALUE)
																															.addComponent(
																																	jButton1))))))
											.addGap(57, 57, 57)
											.addGroup(
													jPanel1Layout
															.createParallelGroup(
																	javax.swing.GroupLayout.Alignment.TRAILING)
															.addComponent(jButton2)
															.addComponent(jButton4)
															.addComponent(jButton6)
															.addComponent(jButton8)
															.addComponent(jButton10))
											.addContainerGap(153, Short.MAX_VALUE)));
			jPanel1Layout
					.setVerticalGroup(jPanel1Layout
							.createParallelGroup(
									javax.swing.GroupLayout.Alignment.LEADING)
							.addGroup(
									jPanel1Layout
											.createSequentialGroup()
											.addGap(37, 37, 37)
											.addGroup(
													jPanel1Layout
															.createParallelGroup(
																	javax.swing.GroupLayout.Alignment.BASELINE)
															.addComponent(
																	jLabel2,
																	javax.swing.GroupLayout.PREFERRED_SIZE,
																	39,
																	javax.swing.GroupLayout.PREFERRED_SIZE)
															.addComponent(jButton1)
															.addComponent(
																	jTextField1,
																	javax.swing.GroupLayout.PREFERRED_SIZE,
																	javax.swing.GroupLayout.DEFAULT_SIZE,
																	javax.swing.GroupLayout.PREFERRED_SIZE)
															.addComponent(jButton2))
											.addPreferredGap(
													javax.swing.LayoutStyle.ComponentPlacement.RELATED)
											.addGroup(
													jPanel1Layout
															.createParallelGroup(
																	javax.swing.GroupLayout.Alignment.BASELINE)
															.addComponent(
																	jLabel4,
																	javax.swing.GroupLayout.PREFERRED_SIZE,
																	39,
																	javax.swing.GroupLayout.PREFERRED_SIZE)
															.addComponent(
																	jTextField2,
																	javax.swing.GroupLayout.PREFERRED_SIZE,
																	javax.swing.GroupLayout.DEFAULT_SIZE,
																	javax.swing.GroupLayout.PREFERRED_SIZE)
															.addComponent(jButton3)
															.addComponent(jButton4))
											.addGap(9, 9, 9)
											.addGroup(
													jPanel1Layout
															.createParallelGroup(
																	javax.swing.GroupLayout.Alignment.BASELINE)
															.addComponent(
																	jLabel6,
																	javax.swing.GroupLayout.PREFERRED_SIZE,
																	39,
																	javax.swing.GroupLayout.PREFERRED_SIZE)
															.addComponent(
																	jTextField3,
																	javax.swing.GroupLayout.PREFERRED_SIZE,
																	javax.swing.GroupLayout.DEFAULT_SIZE,
																	javax.swing.GroupLayout.PREFERRED_SIZE)
															.addComponent(jButton5)
															.addComponent(jButton6))
											.addPreferredGap(
													javax.swing.LayoutStyle.ComponentPlacement.RELATED)
											.addGroup(
													jPanel1Layout
															.createParallelGroup(
																	javax.swing.GroupLayout.Alignment.BASELINE)
															.addComponent(
																	jLabel5,
																	javax.swing.GroupLayout.PREFERRED_SIZE,
																	39,
																	javax.swing.GroupLayout.PREFERRED_SIZE)
															.addComponent(
																	jTextField4,
																	javax.swing.GroupLayout.PREFERRED_SIZE,
																	javax.swing.GroupLayout.DEFAULT_SIZE,
																	javax.swing.GroupLayout.PREFERRED_SIZE)
															.addComponent(jButton7)
															.addComponent(jButton8))
											.addPreferredGap(
													javax.swing.LayoutStyle.ComponentPlacement.RELATED)
											.addGroup(
													jPanel1Layout
															.createParallelGroup(
																	javax.swing.GroupLayout.Alignment.BASELINE)
															.addComponent(
																	jLabel3,
																	javax.swing.GroupLayout.PREFERRED_SIZE,
																	39,
																	javax.swing.GroupLayout.PREFERRED_SIZE)
															.addComponent(
																	jTextField5,
																	javax.swing.GroupLayout.PREFERRED_SIZE,
																	javax.swing.GroupLayout.DEFAULT_SIZE,
																	javax.swing.GroupLayout.PREFERRED_SIZE)
															.addComponent(jButton9)
															.addComponent(jButton10))
											.addContainerGap(58, Short.MAX_VALUE)));

			javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
			this.setLayout(layout);
			layout.setHorizontalGroup(layout
					.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(
							layout.createSequentialGroup()
									.addGroup(
											layout.createParallelGroup(
													javax.swing.GroupLayout.Alignment.LEADING)
													.addGroup(
															layout.createSequentialGroup()
																	.addGap(398,
																			398,
																			398)
																	.addComponent(
																			jLabel1))
													.addGroup(
															layout.createSequentialGroup()
																	.addGap(81, 81,
																			81)
																	.addComponent(
																			jPanel1,
																			javax.swing.GroupLayout.PREFERRED_SIZE,
																			javax.swing.GroupLayout.DEFAULT_SIZE,
																			javax.swing.GroupLayout.PREFERRED_SIZE)))
									.addContainerGap(36, Short.MAX_VALUE)));
			layout.setVerticalGroup(layout.createParallelGroup(
					javax.swing.GroupLayout.Alignment.LEADING).addGroup(
					layout.createSequentialGroup()
							.addGap(32, 32, 32)
							.addComponent(jLabel1,
									javax.swing.GroupLayout.PREFERRED_SIZE, 35,
									javax.swing.GroupLayout.PREFERRED_SIZE)
							.addGap(5, 5, 5)
							.addComponent(jPanel1,
									javax.swing.GroupLayout.PREFERRED_SIZE,
									javax.swing.GroupLayout.DEFAULT_SIZE,
									javax.swing.GroupLayout.PREFERRED_SIZE)
							.addContainerGap(133, Short.MAX_VALUE)));
		}
	public static class MyThred implements Runnable{
		public void run() {
			// TODO Auto-generated method stub
			int A1=0;
			while(true){
				Date dNow = new Date();   //当前时间
				int s=dNow.getSeconds();
				if(s%2==1){
					if(A1==0){
					A1=1;
					if(My_MainFrame.d[0][3]==0){
							if(My_MainFrame.d[0][4]==1){
								jButton1.setEnabled(false);
								jButton2.setEnabled(true);
								jTextField1.setText("原位");
							}else if(My_MainFrame.d[0][4]==0){
								jButton1.setEnabled(true);
								jButton2.setEnabled(false);
								jTextField1.setText("库位");
							}else{
								jButton1.setEnabled(true);
								jButton2.setEnabled(true);
								jTextField1.setText("不明位置");
							}
					}else{
						jButton1.setEnabled(false);
						jButton2.setEnabled(false);
						jTextField1.setText("正在运行");
						}
					if(My_MainFrame.d[2][3]==0){
						if(My_MainFrame.d[2][4]==1){
							jButton3.setEnabled(false);
							jButton4.setEnabled(true);
							jTextField2.setText("原位");
						}else if(My_MainFrame.d[2][4]==0){
							jButton4.setEnabled(false);
							jButton3.setEnabled(true);
							jTextField2.setText("库位");
						}else{
							jButton3.setEnabled(true);
							jButton4.setEnabled(true);
							jTextField2.setText("不明位置");
						}
				}else{
					jButton3.setEnabled(false);
					jButton4.setEnabled(false);
					jTextField2.setText("正在运行");
					}
					if(My_MainFrame.d[4][3]==0){
						if(My_MainFrame.d[4][4]==1){
							jButton5.setEnabled(false);
							jButton6.setEnabled(true);
							jTextField3.setText("原位");
						}else if(My_MainFrame.d[4][4]==0){
							jButton5.setEnabled(true);
							jButton6.setEnabled(false);
							jTextField3.setText("库位");
						}else{
							jButton5.setEnabled(true);
							jButton6.setEnabled(true);
							jTextField3.setText("不明位置");
						}
				}else{
					jButton5.setEnabled(false);
					jButton6.setEnabled(false);
					jTextField3.setText("正在运行");
					}
					if(My_MainFrame.d[6][3]==0){
						if(My_MainFrame.d[6][4]==1){
							jButton7.setEnabled(false);
							jButton8.setEnabled(true);
							jTextField4.setText("原位");
						}else if(My_MainFrame.d[6][4]==0){
							jButton7.setEnabled(true);
							jButton8.setEnabled(false);
							jTextField4.setText("库位");
						}else{
							jButton7.setEnabled(true);
							jButton8.setEnabled(true);
							jTextField4.setText("不明位置");
						}
				}else{
					jButton7.setEnabled(false);
					jButton8.setEnabled(false);
					jTextField4.setText("正在运行");
					}
					if(My_MainFrame.d[8][3]==0){
						if(My_MainFrame.d[8][4]==1){
							jButton9.setEnabled(false);
							jButton10.setEnabled(true);
							jTextField5.setText("原位");
						}else if(My_MainFrame.d[8][4]==0){
							jButton9.setEnabled(true);
							jButton10.setEnabled(false);
							jTextField5.setText("库位");
						}else{
							jButton9.setEnabled(true);
							jButton10.setEnabled(true);
							jTextField5.setText("不明位置");
						}
				}else{
					jButton9.setEnabled(false);
					jButton10.setEnabled(false);
					jTextField5.setText("正在运行");
					}
					}
				}else{
					A1=0;
							
				}
				
			}
		}
		
	}

	private static javax.swing.JButton jButton1;
	private static javax.swing.JButton jButton2;
	private static javax.swing.JButton jButton9;
	private static javax.swing.JButton jButton5;
	private static javax.swing.JButton jButton7;
	private static javax.swing.JButton jButton3;
	private static javax.swing.JButton jButton10;
	private static javax.swing.JButton jButton8;
	private static javax.swing.JButton jButton6;
	private static javax.swing.JButton jButton4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel1;
	private static javax.swing.JTextField jTextField1;
	private static javax.swing.JTextField jTextField2;
	private static javax.swing.JTextField jTextField3;
	private static javax.swing.JTextField jTextField4;
	private static javax.swing.JTextField jTextField5;
	// End of variables declaration//GEN-END:variables

}